language: objective-c
osx_image: xcode9.1
before_install:
    - gem install slather
script:
    - set -o pipefail;
    - xcodebuild -workspace Flat.xcworkspace -scheme "CIScheme" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.1' build test | xcpretty -c
    - pod spec lint --quick
after_success:
    - slather