language: objective-c
osx_image: xcode9.1
script:
    - xcodebuild clean test -workspace Flat.xcworkspace -scheme Flat -destination "platform=iOS Simulator,name=iPhone 8 Plus,OS=11.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
