language: objective-c
osx_image: xcode9.1
script:
    - set -o pipefail && xcodebuild -workspace Flat.xcworkspace -scheme "Flat" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.1' test
